# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j0dGsbDlPs30E0MutqtDFdCAh4OgyPmy
"""

# 📥 Step 1: Preloaded Feedbacks
feedback_data = {
    'S_No': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Name': ['Ravi', 'Meera', 'Sam', 'Anu', 'Raj', 'Divya', 'Arjun', 'Kiran', 'Leela', 'Nisha'],
    'Feedback': [
        ' Very GOOD Service!!!',
        'poor support, not happy ',
        'GREAT experience! will come again.',
        'okay okay...',
        ' not BAD',
        'Excellent care, excellent staff!',
        'good food and good ambience!',
        'Poor response and poor handling of issue',
        'Satisfied. But could be better.',
        'Good support... quick service.'
    ],
    'Rating': [5, 2, 5, 3, 2, 5, 4, 1, 3, 4]
}

# ✍️ Step 2: Add More Feedbacks
n = int(input("How many feedbacks do you want to add? "))

for i in range(n):
    print(f"\nEnter details for feedback {i+1}:")
    name = input("Enter Name: ")
    feedback = input("Enter Feedback: ")
    rating = int(input("Enter Rating (1-5): "))

    feedback_data['S_No'].append(len(feedback_data['S_No']) + 1)
    feedback_data['Name'].append(name)
    feedback_data['Feedback'].append(feedback)
    feedback_data['Rating'].append(rating)

# 🧹 Step 3: Text Cleaning Function
def clean_text(text):
    # Remove punctuation
    for p in ['.', ',', '!', '?']:
        text = text.replace(p, '')

    # Convert to lowercase
    text = text.lower()

    # Remove extra spaces
    text = ' '.join(text.split())

    return text

# Apply cleaning
cleaned_feedbacks = []
for fb in feedback_data['Feedback']:
    cleaned_feedbacks.append(clean_text(fb))

feedback_data['Feedback'] = cleaned_feedbacks

# 🔁 Step 4: Word Count Function
def count_word_in_feedbacks(word):
    count = 0
    for fb in feedback_data['Feedback']:
        words = fb.split()
        if word.lower() in words:
            count += 1
    return count

print("\n📊 Word Count Insights:")
print("Feedbacks containing 'good':", count_word_in_feedbacks("good"))
print("Feedbacks containing 'poor':", count_word_in_feedbacks("poor"))
print("Feedbacks containing 'excellent':", count_word_in_feedbacks("excellent"))

# 📊 Step 5: Final Summary

# Display cleaned data
print("\n📋 Cleaned Feedback Data:")
for i in range(len(feedback_data['S_No'])):
    print(f"{feedback_data['S_No'][i]} | {feedback_data['Name'][i]} | {feedback_data['Feedback'][i]} | Rating: {feedback_data['Rating'][i]}")

# Average rating
avg_rating = sum(feedback_data['Rating']) / len(feedback_data['Rating'])
print("\n⭐ Average Rating:", round(avg_rating, 2))

# Longest feedback (word count)
longest_fb = ""
max_words = 0

for fb in feedback_data['Feedback']:
    word_count = len(fb.split())
    if word_count > max_words:
        max_words = word_count
        longest_fb = fb

print("\n📝 Longest Feedback:")
print(longest_fb)

# Unique words
unique_words = set()

for fb in feedback_data['Feedback']:
    words = fb.split()
    for word in words:
        unique_words.add(word)

print("\n🔤 Unique Words:")
print(unique_words)

# 🧩 Optional: Sort by rating (highest to lowest)
print("\n📈 Sorted Feedbacks (Highest Rating First):")

combined = list(zip(
    feedback_data['S_No'],
    feedback_data['Name'],
    feedback_data['Feedback'],
    feedback_data['Rating']
))

sorted_data = sorted(combined, key=lambda x: x[3], reverse=True)

for item in sorted_data:
    print(item)